name: muqeem
version: 1.0.0+1
description: تطبيق مواقيت الصلاة والعبادات للجزائر - Muqeem
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  geolocator: ^10.1.0
  flutter_compass: ^0.8.0
  adhan: ^2.0.0-nullsafety.2
  http: ^1.1.0
  shared_preferences: ^2.2.2
  hijri: ^3.0.0
  url_launcher: ^6.2.4
  flutter_local_notifications: ^16.3.2
  vibration: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png 